name: Feature Request
description: Suggest an improvement or feature for Core Platform
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement or feature!

  - type: dropdown
    id: feature_area
    attributes:
      label: Feature Area
      options:
        - Authentication
        - User Management
        - API Gateway
        - Logging/Monitoring
        - Infrastructure
        - Security
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the feature or improvement
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature should be added
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the high-level features and functionality required
    validations:
      required: true

  - type: textarea
    id: extra_context
    attributes:
      label: Extra Context
      description: Add any other context or screenshots
    validations:
      required: false
